use_frameworks!

target 'TimePickerPod_Example' do
  pod 'TimePickerPod', :path => '../'

  target 'TimePickerPod_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'FontAwesome.swift', '~> 1.8'
  end
end
